name: Run ECS Task Action
description: Runs a standalone ECS task
inputs:
  task_definition_family:
    description: The name of the Task Definition Family
    required: true
  task_launch_type:
    description: The task launch type. (EC2 or FARGATE)
    required: false
    default: FARGATE
  task_cluster:
    description: The ECS cluster to run the task in
    required: true
  task_subnets:
    description: A comma separated list of subnet names in which the task can be started
    required: true
  is_public_subnet:
    description: Are the task subnets public? (ECS Task needs Public IP assigned)
    required: true
  task_security_groups:
    description: A comma separated list of Security Group names to assign to the task
    required: true
  task_region:
    description: The AWS region to run the task in
    required: true
  task_command_override:
    description: Optional command to run in the task's container instead of the default command
    required: false

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.task_definition_family }}
    - ${{ inputs.task_launch_type }}
    - ${{ inputs.task_cluster }}
    - ${{ inputs.task_subnets }}
    - ${{ inputs.is_public_subnet }}
    - ${{ inputs.task_security_groups }}
    - ${{ inputs.task_region }}
    - ${{ inputs.task_command_override }}
