name: 'Generate Markdown Action'
description: 'Generate markdown for the PostgreSQL Scheam created by this repository'
inputs:
  postgres_db:
    description: 'The name of the database to generate the schema markdown from'
    required: true
    default: 'auroradb_ci'
  postgres_user:
    description: 'The username to connect to the db'
    required: true
    default: 'postgres'
  postgres_password:
    description: 'The password to connect to the db'
    required: true
    default: 'password'
  gitbot_email:
    description: 'The email used to make commits to update README.md'
    required: true
    default: 'aurora.gitbot@example.com'
  gitbot_name:
    description: 'The name used to make commits to update README.md'
    required: true
    default: 'aurora-gitbot'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    POSTGRES_DB: ${{ inputs.postgres_db }}
    POSTGRES_USER: ${{ inputs.postgres_user }}
    POSTGRES_PASSWORD: ${{ inputs.postgres_password }}
    GITBOT_EMAIL: ${{ inputs.gitbot_email }}
    GITBOT_NAME: ${{ inputs.gitbot_name }}
