name: 'Generate Markdown Action'
description: 'Generate markdown for the PostgreSQL Scheam created by this repository'
inputs:
  postgres_db:
    description: 'The name of the database to generate the schema markdown from'
    required: true
    default: 'auroradb_ci_local'
  postgres_user:
    description: 'The username to connect to the db'
    required: true
    default: 'postgres'
  postgres_password:
    description: 'The password to connect to the db'
    required: true
    default: 'password'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    POSTGRES_DB: ${{ inputs.postgres_db }}
    POSTGRES_USER: ${{ inputs.postgres_user }}
    POSTGRES_PASSWORD: ${{ inputs.postgres_password }}
