name: Build Flyway Docker Image for ECS Task
on:
  repository_dispatch:
    types: build_flyway
  push:
    paths:
    - 'docker/**'
jobs:
  build-flyway:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Flyway Docker Image
        run: ./scripts/build_flyway_docker_image.sh
