name: Build Flyway Docker Image for ECS Task
on:
  repository_dispatch:
    types: build_flyway
  push:
    paths:
    - 'docker/**'
jobs:
  build-flyway:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Flyway Docker Image
        run: |
          image_tag="$(cat config.json | jq -r '.flywayVersion')"
          echo ${GITHUB_REF}
          if [[ $GITHUB_REF != 'refs/head/master' ]]; then
            image_tag="${image_tag}.${GITHUB_RUN_ID}"
          fi

          echo "${image_tag}"

          echo "${{ github.token }}" | docker login docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin
          docker build -t "docker.pkg.github.com/sharebuilder-401k/aurora-serverless-flyway-db/flyway:${image_tag}" ./docker
          docker tag docker.pkg.github.com/sharebuilder-401k/aurora-serverless-flyway-db/flyway:${image_tag} docker.pkg.github.com/sharebuilder-401k/aurora-serverless-flyway-db/flyway:latest
          docker push docker.pkg.github.com/sharebuilder-401k/aurora-serverless-flyway-db/flyway:${image_tag}
          docker push docker.pkg.github.com/sharebuilder-401k/aurora-serverless-flyway-db/flyway:latest

          sed -i "s/app_version =.*/app_version = \"${image_tag}\"/" "infrastructure/flyway-fargate-task/var-files/us-west-2.tfvars"

          git config user.email aurora.gitbot@example.com
          git config user.name aurora-gitbot
          git add "infrastructure/flyway-fargate-task/var-files/us-west-2.tfvars"
          git commit -m "Updating flyway app_version from GitHub Actions"
          git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
