name: 'Deploy Terraform Infrastructure'
on:
  repository_dispatch:
    types: deploy_infrastructure
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './infrastructure/${{ github.event.client_payload.infrastructure_folder }}'
    env:
      AWS_DEFAULT_REGION: ${{ github.event.client_payload.region }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ~0.12.24

      - name: Terraform Init
        run: terraform init -backend-config="region=${{ github.event.client_payload.region }}" -backend-config="bucket=${{ github.event.client_payload.bucket }}"

      - name: Terraform Apply
        run: terraform apply -var-file="var-files/${{ github.event.client_payload.region }}.tfvars" -auto-approve
