name: 'Destroy Terraform Infrastructure'
on:
  repository_dispatch:
    types: destroy_infrastructure
jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ${{ github.event.client_payload.region }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './infrastructure/${{ github.event.client_payload.infrastructure_folder }}'
          tf_actions_comment: true
          args: "-backend-config=\"region=${{ github.event.client_payload.region }}\" --backend-config=\"bucket=${{ github.event.client_payload.bucket }}\""

      - name: 'Terraform Destroy'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'destroy'
          tf_actions_working_dir: './infrastructure/${{ github.event.client_payload.infrastructure_folder }}'
          tf_actions_comment: true
          args: "--var-file=\"var-files/${{ github.event.client_payload.region }}.tfvars\""
