name: Run Flyway Migration
on:
  repository_dispatch:
    types: run_migration
jobs:
  run_migration:
    runs-on: ubuntu-latest
    env:
        AWS_DEFAULT_REGION: ${{ github.event.client_payload.region }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Flyway Migration
        uses: ./.github/actions/run-ecs-task-action
        with:
          task_definition_family: ${{ github.event.client_payload.task_definition_family }}
          task_launch_type: ${{ github.event.client_payload.task_launch_type }}
          task_cluster: ${{ github.event.client_payload.task_cluster }}
          task_subnets: ${{ github.event.client_payload.task_subnets }}
          is_public_subnet: ${{ github.event.client_payload.is_public_subnet }}
          task_security_groups: ${{ github.event.client_payload.task_security_groups }}
          task_region: ${{ github.event.client_payload.region }}
          task_command_override: /flyway/scripts/flyway-rds-migration.sh ${{ github.event.client_payload.branch }}
